// Generated by CoffeeScript 1.9.1
(function() {
  var UIComponent, root;

  UIComponent = (function() {
    UIComponent.prototype.iframeElement = null;

    UIComponent.prototype.iframePort = null;

    UIComponent.prototype.showing = null;

    function UIComponent(iframeUrl, className, handleMessage) {
      this.handleMessage = handleMessage;
      this.iframeElement = document.createElement("iframe");
      this.iframeElement.className = className;
      this.iframeElement.seamless = "seamless";
      this.iframeElement.src = chrome.runtime.getURL(iframeUrl);
      this.iframeElement.addEventListener("load", (function(_this) {
        return function() {
          return _this.openPort();
        };
      })(this));
      document.documentElement.appendChild(this.iframeElement);
      this.showing = true;
      this.hide(false);
    }

    UIComponent.prototype.openPort = function() {
      var messageChannel;
      messageChannel = new MessageChannel();
      this.iframePort = messageChannel.port1;
      this.iframePort.onmessage = (function(_this) {
        return function(event) {
          return _this.handleMessage(event);
        };
      })(this);
      return chrome.storage.local.get("vimiumSecret", (function(_this) {
        return function(arg) {
          var secret;
          secret = arg.vimiumSecret;
          return _this.iframeElement.contentWindow.postMessage(secret, chrome.runtime.getURL(""), [messageChannel.port2]);
        };
      })(this));
    };

    UIComponent.prototype.postMessage = function(message) {
      return this.iframePort.postMessage(message);
    };

    UIComponent.prototype.activate = function(message) {
      if (message != null) {
        this.postMessage(message);
      }
      if (!this.showing) {
        this.show();
      }
      return this.iframeElement.focus();
    };

    UIComponent.prototype.show = function(message) {
      if (message != null) {
        this.postMessage(message);
      }
      this.iframeElement.classList.remove("vimiumUIComponentHidden");
      this.iframeElement.classList.add("vimiumUIComponentShowing");
      window.addEventListener("focus", this.onFocus = (function(_this) {
        return function(event) {
          if (event.target === window) {
            window.removeEventListener("focus", _this.onFocus);
            _this.onFocus = null;
            return _this.postMessage("hide");
          }
        };
      })(this));
      return this.showing = true;
    };

    UIComponent.prototype.hide = function(focusWindow) {
      if (focusWindow == null) {
        focusWindow = true;
      }
      this.iframeElement.classList.remove("vimiumUIComponentShowing");
      this.iframeElement.classList.add("vimiumUIComponentHidden");
      if (this.onFocus) {
        window.removeEventListener("focus", this.onFocus);
      }
      this.onFocus = null;
      if (focusWindow) {
        window.focus();
      }
      return this.showing = false;
    };

    return UIComponent;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.UIComponent = UIComponent;

}).call(this);
